name: Sign Git Tag with Gitsign

on:
  push:
    tags:
      - '*'

jobs:
  sign-tag:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get the tag name
      id: tag_name
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Debug, remove me later
      run: echo "The tag is ${{ env.TAG_NAME }}"

    - name: Install gitsign
      run: |
        curl -Lo gitsign https://github.com/sigstore/gitsign/releases/download/v0.8.0/gitsign_0.8.0_linux_arm64
        chmod +x gitsign
        sudo mv gitsign /usr/local/bin/

    - name: Configure gitsign
      run: |
        # https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key#telling-git-about-your-x509-key
        git config --global gpg.x509.program gitsign
        git config --global gpg.format x509
        # FIXME: should this be an annotated tag, e.g. tag.forceSignAnnotated ?
        git config --global tag.gpgSign
